### ISSUE TITLE
删除好友功能存在bug

### ISSUE THREAD

**Issue by Tang-Chenhang** [Wang-Decheng/ChatApp#23]
发送删除好友的请求包后，服务器不会返回响应。
删除好友后重新请求好友状态，发现好友并没有被删除
![image](https://github.com/Wang-Decheng/ChatApp/assets/92939023/3ddf920c-ed68-45aa-8649-7a20f049a6c9)

ps：user_manager中删除好友的函数与server中删除好友时调用的函数名称不一致
![image](https://github.com/Wang-Decheng/ChatApp/assets/92939023/90e40e56-b76f-4374-9383-74d97a416bb5)
![image](https://github.com/Wang-Decheng/ChatApp/assets/92939023/c34e595e-d64a-48df-89cb-1b06031cbccf)

**Comment by Wang-Decheng** [comment]
[commit 334e76d](https://github.com/Wang-Decheng/ChatApp/commit/334e76d0e4eb7fffe72cd9d494347becb0bd30d3)

**Comment by Wang-Decheng** [comment]
已在下午修复，请确认是否及时更新了main

**Comment by Tang-Chenhang** [comment]
在更新main分支后，测试删除好友功能。
删除好友后获取好友状态，发现好友关系仍然存在。
![image](https://github.com/Wang-Decheng/ChatApp/assets/92939023/f0cc583c-b798-4a3e-92fa-1ce1ab950513)

**Comment by Wang-Decheng** [comment]
确认一下user2已经注册了没有，根据返回信息看，没有在user列表中查询到有user2

**Comment by Tang-Chenhang** [comment]
user1和user2均在线，在user1上请求删除user2
![image](https://github.com/Wang-Decheng/ChatApp/assets/92939023/b90ddb5c-e612-42ab-9950-a6c167a4a204)

**Comment by YoungZSh** [comment]
跟我下午上课的时候遇到的bug一模一样 @Wang-Decheng

**Comment by Wang-Decheng** [comment]
我去看看

**Comment by Wang-Decheng** [comment]
@Tang-Chenhang 点击删除好友按钮没有任何反应正常吗

**Comment by Tang-Chenhang** [comment]
> @Tang-Chenhang 点击删除好友按钮没有任何反应正常吗

我提交的版本没有给删除好友功能没有做完，只是做了一个按钮，没有绑定函数。
需要的话现在我把删除好友功能完善过的PR上去
